name: Issue Date Tracker
on:
  issues:
    types: [opened, closed]
  
jobs:
  track-issue-dates:
    runs-on: ubuntu-latest
    environment: project-env
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Set start date when issue is opened
        if: github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          
          echo "Using Project ID: ${PROJECT_ID}"
          
          gh api graphql -f query='
            mutation (
              $project_id: ID!
              $item_id: ID!
              $date: Date!
            ) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project_id
                itemId: $item_id
                fieldId: "PVTF_lAHOBzKH4s4AouiozggQEAE"
                value: { date: $date }
              }) {
                projectV2Item {
                  id
                }
              }
            }' \
            -f project_id="${PROJECT_ID}" \
            -f item_id="${ISSUE_NODE_ID}" \
            -f date="${TODAY}"
            
      - name: Set end date when issue is closed
        if: github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          
          echo "Using Project ID: ${PROJECT_ID}"
          
          gh api graphql -f query='
            mutation (
              $project_id: ID!
              $item_id: ID!
              $date: Date!
            ) {
              updateProjectV2ItemFieldValue(input: {
                projectId: $project_id
                itemId: $item_id
                fieldId: "PVTF_lAHOBzKH4s4AouiozggQEAE"
                value: { date: $date }
              }) {
                projectV2Item {
                  id
                }
              }
            }' \
            -f project_id="${PROJECT_ID}" \
            -f item_id="${ISSUE_NODE_ID}" \
            -f date="${TODAY}"
